[tool.black]
line-length = 88
target-version = ['py311']
exclude = '''
/(
    \.venv
  | build
  | dist
  | __pycache__
)/
'''

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict_optional = true
disallow_untyped_defs = true
check_untyped_defs = true
show_error_codes = true
exclude = "venv|build|tests"
