name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check for unsafe torch.load() usage
      run: |
        bash scripts/check_torch_load.sh
    
    # Add other security and test steps here
    - name: Run Bandit security scanner
      run: |
        pip install bandit
        bandit -r . --exclude .git,__pycache__,venv,build,dist,code_quality --skip B404,B603
    
    - name: Run code quality checks
      run: |
        pip install black flake8 mypy
        black --check .
        flake8 .
        mypy .
