name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  code-quality:
    name: Run Code Quality Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pre-commit black isort flake8 mypy bandit pyupgrade pycln detect-secrets

    - name: Create reports directory
      run: mkdir -p code_quality/code_quality_reports

    - name: Run pre-commit hooks
      run: |
        pre-commit install
        pre-commit run --all-files > code_quality/code_quality_reports/pre_commit_report.txt 2>&1 || true

    - name: Run security scan
      run: |
        bandit -r . -c .bandit -f txt -o code_quality/code_quality_reports/bandit_report_$(date +%Y%m%d_%H%M%S).txt || true

    - name: Run type checking
      run: |
        mypy --config-file=pyproject.toml . > code_quality/code_quality_reports/mypy_report_$(date +%Y%m%d_%H%M%S).txt 2>&1 || true

    - name: Run linting
      run: |
        flake8 . --config=setup.cfg > code_quality/code_quality_reports/flake8_report_$(date +%Y%m%d_%H%M%S).txt 2>&1 || true

    - name: Check formatting
      run: |
        black --check . --config pyproject.toml > code_quality/code_quality_reports/black_report_$(date +%Y%m%d_%H%M%S).txt 2>&1 || true
        isort --check-only --settings-path pyproject.toml . > code_quality/code_quality_reports/isort_report_$(date +%Y%m%d_%H%M%S).txt 2>&1 || true

    - name: Run Code Quality Checker
      run: |
        python -m code_quality.CodeQualityChecker -o code_quality/code_quality_reports/code_quality_report_$(date +%Y%m%d_%H%M%S).txt

    - name: Upload Code Quality Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: code-quality-report
        path: code_quality/code_quality_reports/
        retention-days: 7

  # Additional job for dependency vulnerability scanning
  dependency-scan:
    name: Dependency Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install safety
      run: pip install safety
    - name: Run safety check
      run: safety check --full-report
